/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'ferry' at '6/13/15 7:35 PM' with Gradle 2.2.1
 *
 * @author ferry, @date 6/13/15 7:35 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
